Server:
  Mode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTime: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
JWT:
  secret: this is a debug JWT secret
  Issuer: xusheng:20691718@qq.com
  Expire: 7200
PG:
  DBName: time-frequency
  Username: time-frequency
  Password: time-frequency
  Host: home.xuxusheng.com:30681