definitions:
  model.DWithP:
    properties:
      data:
        type: object
      pn:
        description: 当前页码
        type: integer
      ps:
        description: 每页显示记录数
        type: integer
      total:
        description: 总共多少条记录
        type: integer
    type: object
  model.ErrMeta:
    properties:
      err_code:
        description: 错误码
        example: 10000000
        type: integer
      err_details:
        description: 错误详情
        items:
          type: string
        type: array
      err_msg:
        description: 错误信息
        example: 服务器内部错误
        type: string
    type: object
  model.ErrResp:
    properties:
      data:
        type: object
      meta:
        $ref: '#/definitions/model.ErrMeta'
    type: object
  model.Meta:
    properties:
      err_code:
        description: 错误码
        example: 0
        type: integer
      err_details:
        description: 错误详情
        items:
          type: string
        type: array
      err_msg:
        description: 错误信息
        example: 成功
        type: string
    type: object
  model.Resp:
    properties:
      data:
        type: object
      meta:
        $ref: '#/definitions/model.Meta'
    type: object
  model.User:
    properties:
      created_at:
        example: "2020-12-09T18:52:41.555+08:00"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: xusheng
        type: string
      phone:
        example: "17707272442"
        type: string
      role:
        example: member
        type: string
      updated_at:
        example: "2020-12-09T18:52:41.555+08:00"
        type: string
    type: object
info:
  contact:
    email: 20691718@qq.com
    name: xusheng
    url: https://github.com/xuxusheng
  description: 时频学习平台后端接口文档
  title: 时频学习平台
  version: "1.0"
paths:
  /api/v1/users:
    get:
      consumes:
      - application/json
      description: 通过 name、phone 字段查询匹配的用户，支持模糊查询、分页
      parameters:
      - default: ""
        description: 用户名
        in: query
        name: name
        type: string
      - default: ""
        description: 手机号
        in: query
        name: phone
        type: string
      - default: "1"
        description: 第几页
        in: query
        name: pn
        type: string
      - default: "10"
        description: 每页记录数量
        in: query
        name: ps
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Resp'
            - properties:
                data:
                  allOf:
                  - $ref: '#/definitions/model.DWithP'
                  - properties:
                      data:
                        items:
                          $ref: '#/definitions/model.User'
                        type: array
                    type: object
              type: object
      summary: 分页获取用户列表
      tags:
      - user
    post:
      consumes:
      - application/json
      description: 创建新用户接口，专供管理平台调用
      parameters:
      - description: 用户名（6 - 20 位数字或字母构成)
        in: body
        maxLength: 20
        minLength: 6
        name: name
        required: true
        schema:
          type: string
      - description: 手机号（11 位数字）
        in: body
        maxLength: 11
        minLength: 11
        name: phone
        required: true
        schema:
          type: string
      - description: 密码（6 - 20 位字符）
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
        "500":
          description: 内部错误
          schema:
            $ref: '#/definitions/model.ErrResp'
      summary: 创建新用户
      tags:
      - user
  /api/v1/users/{id}:
    delete:
      consumes:
      - application/json
      description: 根据 ID 删除用户
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Resp'
      summary: 删除用户
      tags:
      - user
    get:
      consumes:
      - application/json
      description: 通过 ID 查询单个用户详细信息
      parameters:
      - description: 用户ID
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      summary: 查询单个用户
      tags:
      - user
    put:
      consumes:
      - application/json
      description: |-
        更新用户名、手机号等，字段不传或为空字符串不修改此字段。
        只针对用户基本信息修改，其他信息例如角色、密码等，通过专门的接口改，便于权限控制。
      parameters:
      - description: 用户ID
        in: path
        name: id
        required: true
        type: integer
      - description: 用户名
        in: body
        name: name
        schema:
          type: string
      - description: 手机号
        in: body
        name: phone
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.Resp'
            - properties:
                data:
                  $ref: '#/definitions/model.User'
              type: object
      summary: 更新用户信息
      tags:
      - user
swagger: "2.0"
